### ISSUE TITLE
IOError with no collection file

### ISSUE THREAD

**Issue by tlvince** [richardpeng/Kindelabra#2]
If there is no pre-existing `collections.json` (on the Kindle), an `IOError` is thrown:

```
$ python2 Kindelabra.py 
Traceback (most recent call last):
  File "Kindelabra.py", line 107, in load
    self.db = kindle.CollectionDB(self.colfile)
  File "/tmp/Kindelabra/kindle.py", line 34, in __init__
    with open(colfile) as colfile:
IOError: [Errno 2] No such file or directory: '/media/Kindle/system/collections.json'
Loading documents............................
Loading pictures
```

When trying to create a new collection (using Kindelabra) an `AttributeError` is thrown:

```
Traceback (most recent call last):
  File "Kindelabra.py", line 152, in add_collection
    if not colname in self.db:
AttributeError: KindleUI instance has no attribute 'db'
```

Kindelabra #adf278f

**Comment by Tritlo** [comment]
I've put a pull request for a fix.
